config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "messages#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /messages or /messages.json
  def index
    @messages = Message.all.order("created_at DESC")
    @message = Message.new
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = current_user.messages.build
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = current_user.messages.build(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to root_path, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:message)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messageboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class = "notification is-primary global-notification">
        <p class = "notice"><%= notice %></p>
      </div>
    <% end %>
    <%if flash[:alert]%>
      <div class = "notification is-danger global-notification">
        <p class = "alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do%>
        <h1 class="title is-5">Messageboard</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
       </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Message', new_message_path, class: "button is-info is-inverted"%>
            </p>
            <%if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path , class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <%end%>

          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/messages/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'messages/form' %>
        </div>
    </article>
    <% end %>


<% @messages.each do | message | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class= "image is 64x64">
                    <%= gravatar_image_tag(message.user.email, size: 64, alt: message.user.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%= message.user.name %></strong><br />
                    <small><%= message.user.username %><small><br/>
                    <p><%= message.message %></p>
                </div>
                <% if user_signed_in?%>
                <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to message, class: "level-item" do %>
                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_message_path(message), class: "level-item" do %>
                            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to message, method: :delete, data: { confirm: "Are you sure you want to delete this message?"
                        } do %>
                            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
                <% end %>
            </div>
        </article>
    </div>
<% end %>
</div>

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :message, label: "What's on your mind?", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a message..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Message:</strong>
    <%= message.message %>
  </p>

</div>

app/views/messages/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Messages</p>
						<p class="title is-6"><%= current_user.messages.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/messages/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="pannel-heading">Trends</p>
        <a class="panel-block">
            Trend
        </a>

    </nav>
</div>

app/views/messages/_who-to-follow.html.erb
<div class="column">
    <nav class="pannel">
        <p class="pannel-heading">Who to Follow</p>
    </nav>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is 32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            <div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Joe Doe</strong>
                        <small>@joed</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is 32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            <div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Joe Doe</strong>
                        <small>@joed</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is 32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            <div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Joe Doe</strong>
                        <small>@joed</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    


</div>

app/views/messages/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Message</h1>
				<%= render 'form', message: @message %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', messages_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/messages/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in?%>
      <%= render 'profile' %>
    <% else %>
      <%= render 'trends'%>
    <% end %>

      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/messages/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Message</h1>
					<%= render 'form', message: @message %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', messages_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>